### ISSUE TITLE
Discord Linking Falsely Erroring

### ISSUE THREAD

**Issue by aggelosQQ** [UnraveledMC/Control-Panel-Bot#1]
![Discord Error](https://aggelos.doesnt-have-a.life/iwvw79e.png)

**Comment by Raduyno** [comment]
That is a old error. It links your acc tho.

**Comment by aggelosQQ** [comment]
If there is no way to fix it, you shall close the issue.

**Comment by CreeperSeth** [comment]
For anyone wondering what causes it, it's from DiscordSRV. It has a pointless account linking system on it that uses 4 digit codes.

**Comment by CreeperSeth** [comment]
Also, this has nothing to do with the control panel bot. The verification system is in the UnraveledMCMod plugin.
